export default {
  login: "Sushant2",
  id: 56200805,
  node_id: "MDQ6VXNlcjU2MjAwODA1",
  avatar_url: "https://avatars.githubusercontent.com/u/56200805?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Sushant2",
  html_url: "https://github.com/Sushant2",
  followers_url: "https://api.github.com/users/Sushant2/followers",
  following_url: "https://api.github.com/users/Sushant2/following{/other_user}",
  gists_url: "https://api.github.com/users/Sushant2/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Sushant2/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Sushant2/subscriptions",
  organizations_url: "https://api.github.com/users/Sushant2/orgs",
  repos_url: "https://api.github.com/users/Sushant2/repos",
  events_url: "https://api.github.com/users/Sushant2/events{/privacy}",
  received_events_url: "https://api.github.com/users/Sushant2/received_events",
  type: "User",
  site_admin: false,
  name: "Light Yagami",
  company: null,
  blog: "https://sourcerer.io/sushant2",
  location: "New Delhi,India",
  email: null,
  hireable: null,
  bio: "Web | Autodidact | Computer Science",
  twitter_username: "er_sushant_",
  public_repos: 43,
  public_gists: 3,
  followers: 15,
  following: 19,
  created_at: "2019-10-05T16:26:30Z",
  updated_at: "2021-05-24T16:11:46Z",
};
