export default[
  {
    login: "imyogeshgaur",
    id: 57908494,
    node_id: "MDQ6VXNlcjU3OTA4NDk0",
    avatar_url: "https://avatars.githubusercontent.com/u/57908494?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/imyogeshgaur",
    html_url: "https://github.com/imyogeshgaur",
    followers_url: "https://api.github.com/users/imyogeshgaur/followers",
    following_url:
      "https://api.github.com/users/imyogeshgaur/following{/other_user}",
    gists_url: "https://api.github.com/users/imyogeshgaur/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/imyogeshgaur/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/imyogeshgaur/subscriptions",
    organizations_url: "https://api.github.com/users/imyogeshgaur/orgs",
    repos_url: "https://api.github.com/users/imyogeshgaur/repos",
    events_url: "https://api.github.com/users/imyogeshgaur/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/imyogeshgaur/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "badal-cloud",
    id: 56346262,
    node_id: "MDQ6VXNlcjU2MzQ2MjYy",
    avatar_url: "https://avatars.githubusercontent.com/u/56346262?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/badal-cloud",
    html_url: "https://github.com/badal-cloud",
    followers_url: "https://api.github.com/users/badal-cloud/followers",
    following_url:
      "https://api.github.com/users/badal-cloud/following{/other_user}",
    gists_url: "https://api.github.com/users/badal-cloud/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/badal-cloud/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/badal-cloud/subscriptions",
    organizations_url: "https://api.github.com/users/badal-cloud/orgs",
    repos_url: "https://api.github.com/users/badal-cloud/repos",
    events_url: "https://api.github.com/users/badal-cloud/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/badal-cloud/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Priyankcoder",
    id: 39910453,
    node_id: "MDQ6VXNlcjM5OTEwNDUz",
    avatar_url: "https://avatars.githubusercontent.com/u/39910453?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Priyankcoder",
    html_url: "https://github.com/Priyankcoder",
    followers_url: "https://api.github.com/users/Priyankcoder/followers",
    following_url:
      "https://api.github.com/users/Priyankcoder/following{/other_user}",
    gists_url: "https://api.github.com/users/Priyankcoder/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Priyankcoder/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Priyankcoder/subscriptions",
    organizations_url: "https://api.github.com/users/Priyankcoder/orgs",
    repos_url: "https://api.github.com/users/Priyankcoder/repos",
    events_url: "https://api.github.com/users/Priyankcoder/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Priyankcoder/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Harshal0506",
    id: 66555099,
    node_id: "MDQ6VXNlcjY2NTU1MDk5",
    avatar_url: "https://avatars.githubusercontent.com/u/66555099?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Harshal0506",
    html_url: "https://github.com/Harshal0506",
    followers_url: "https://api.github.com/users/Harshal0506/followers",
    following_url:
      "https://api.github.com/users/Harshal0506/following{/other_user}",
    gists_url: "https://api.github.com/users/Harshal0506/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Harshal0506/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Harshal0506/subscriptions",
    organizations_url: "https://api.github.com/users/Harshal0506/orgs",
    repos_url: "https://api.github.com/users/Harshal0506/repos",
    events_url: "https://api.github.com/users/Harshal0506/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Harshal0506/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "iamrahulpanchal",
    id: 39897999,
    node_id: "MDQ6VXNlcjM5ODk3OTk5",
    avatar_url: "https://avatars.githubusercontent.com/u/39897999?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/iamrahulpanchal",
    html_url: "https://github.com/iamrahulpanchal",
    followers_url: "https://api.github.com/users/iamrahulpanchal/followers",
    following_url:
      "https://api.github.com/users/iamrahulpanchal/following{/other_user}",
    gists_url: "https://api.github.com/users/iamrahulpanchal/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/iamrahulpanchal/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/iamrahulpanchal/subscriptions",
    organizations_url: "https://api.github.com/users/iamrahulpanchal/orgs",
    repos_url: "https://api.github.com/users/iamrahulpanchal/repos",
    events_url: "https://api.github.com/users/iamrahulpanchal/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/iamrahulpanchal/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "technoweirds",
    id: 69467316,
    node_id: "MDQ6VXNlcjY5NDY3MzE2",
    avatar_url: "https://avatars.githubusercontent.com/u/69467316?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/technoweirds",
    html_url: "https://github.com/technoweirds",
    followers_url: "https://api.github.com/users/technoweirds/followers",
    following_url:
      "https://api.github.com/users/technoweirds/following{/other_user}",
    gists_url: "https://api.github.com/users/technoweirds/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/technoweirds/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/technoweirds/subscriptions",
    organizations_url: "https://api.github.com/users/technoweirds/orgs",
    repos_url: "https://api.github.com/users/technoweirds/repos",
    events_url: "https://api.github.com/users/technoweirds/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/technoweirds/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "tispn",
    id: 64691616,
    node_id: "MDQ6VXNlcjY0NjkxNjE2",
    avatar_url: "https://avatars.githubusercontent.com/u/64691616?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/tispn",
    html_url: "https://github.com/tispn",
    followers_url: "https://api.github.com/users/tispn/followers",
    following_url: "https://api.github.com/users/tispn/following{/other_user}",
    gists_url: "https://api.github.com/users/tispn/gists{/gist_id}",
    starred_url: "https://api.github.com/users/tispn/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/tispn/subscriptions",
    organizations_url: "https://api.github.com/users/tispn/orgs",
    repos_url: "https://api.github.com/users/tispn/repos",
    events_url: "https://api.github.com/users/tispn/events{/privacy}",
    received_events_url: "https://api.github.com/users/tispn/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "imabp",
    id: 53480076,
    node_id: "MDQ6VXNlcjUzNDgwMDc2",
    avatar_url: "https://avatars.githubusercontent.com/u/53480076?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/imabp",
    html_url: "https://github.com/imabp",
    followers_url: "https://api.github.com/users/imabp/followers",
    following_url: "https://api.github.com/users/imabp/following{/other_user}",
    gists_url: "https://api.github.com/users/imabp/gists{/gist_id}",
    starred_url: "https://api.github.com/users/imabp/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/imabp/subscriptions",
    organizations_url: "https://api.github.com/users/imabp/orgs",
    repos_url: "https://api.github.com/users/imabp/repos",
    events_url: "https://api.github.com/users/imabp/events{/privacy}",
    received_events_url: "https://api.github.com/users/imabp/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "CoDeRShArAd",
    id: 62346689,
    node_id: "MDQ6VXNlcjYyMzQ2Njg5",
    avatar_url: "https://avatars.githubusercontent.com/u/62346689?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/CoDeRShArAd",
    html_url: "https://github.com/CoDeRShArAd",
    followers_url: "https://api.github.com/users/CoDeRShArAd/followers",
    following_url:
      "https://api.github.com/users/CoDeRShArAd/following{/other_user}",
    gists_url: "https://api.github.com/users/CoDeRShArAd/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/CoDeRShArAd/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/CoDeRShArAd/subscriptions",
    organizations_url: "https://api.github.com/users/CoDeRShArAd/orgs",
    repos_url: "https://api.github.com/users/CoDeRShArAd/repos",
    events_url: "https://api.github.com/users/CoDeRShArAd/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/CoDeRShArAd/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Varun4801",
    id: 76906461,
    node_id: "MDQ6VXNlcjc2OTA2NDYx",
    avatar_url: "https://avatars.githubusercontent.com/u/76906461?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Varun4801",
    html_url: "https://github.com/Varun4801",
    followers_url: "https://api.github.com/users/Varun4801/followers",
    following_url:
      "https://api.github.com/users/Varun4801/following{/other_user}",
    gists_url: "https://api.github.com/users/Varun4801/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Varun4801/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Varun4801/subscriptions",
    organizations_url: "https://api.github.com/users/Varun4801/orgs",
    repos_url: "https://api.github.com/users/Varun4801/repos",
    events_url: "https://api.github.com/users/Varun4801/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Varun4801/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "rahulvchowdary",
    id: 76838298,
    node_id: "MDQ6VXNlcjc2ODM4Mjk4",
    avatar_url: "https://avatars.githubusercontent.com/u/76838298?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/rahulvchowdary",
    html_url: "https://github.com/rahulvchowdary",
    followers_url: "https://api.github.com/users/rahulvchowdary/followers",
    following_url:
      "https://api.github.com/users/rahulvchowdary/following{/other_user}",
    gists_url: "https://api.github.com/users/rahulvchowdary/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/rahulvchowdary/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/rahulvchowdary/subscriptions",
    organizations_url: "https://api.github.com/users/rahulvchowdary/orgs",
    repos_url: "https://api.github.com/users/rahulvchowdary/repos",
    events_url: "https://api.github.com/users/rahulvchowdary/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/rahulvchowdary/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "akm-akm",
    id: 67242659,
    node_id: "MDQ6VXNlcjY3MjQyNjU5",
    avatar_url: "https://avatars.githubusercontent.com/u/67242659?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/akm-akm",
    html_url: "https://github.com/akm-akm",
    followers_url: "https://api.github.com/users/akm-akm/followers",
    following_url:
      "https://api.github.com/users/akm-akm/following{/other_user}",
    gists_url: "https://api.github.com/users/akm-akm/gists{/gist_id}",
    starred_url: "https://api.github.com/users/akm-akm/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/akm-akm/subscriptions",
    organizations_url: "https://api.github.com/users/akm-akm/orgs",
    repos_url: "https://api.github.com/users/akm-akm/repos",
    events_url: "https://api.github.com/users/akm-akm/events{/privacy}",
    received_events_url: "https://api.github.com/users/akm-akm/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "arnoob16",
    id: 49037005,
    node_id: "MDQ6VXNlcjQ5MDM3MDA1",
    avatar_url: "https://avatars.githubusercontent.com/u/49037005?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/arnoob16",
    html_url: "https://github.com/arnoob16",
    followers_url: "https://api.github.com/users/arnoob16/followers",
    following_url:
      "https://api.github.com/users/arnoob16/following{/other_user}",
    gists_url: "https://api.github.com/users/arnoob16/gists{/gist_id}",
    starred_url: "https://api.github.com/users/arnoob16/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/arnoob16/subscriptions",
    organizations_url: "https://api.github.com/users/arnoob16/orgs",
    repos_url: "https://api.github.com/users/arnoob16/repos",
    events_url: "https://api.github.com/users/arnoob16/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/arnoob16/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mad-skull",
    id: 53872525,
    node_id: "MDQ6VXNlcjUzODcyNTI1",
    avatar_url: "https://avatars.githubusercontent.com/u/53872525?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mad-skull",
    html_url: "https://github.com/mad-skull",
    followers_url: "https://api.github.com/users/mad-skull/followers",
    following_url:
      "https://api.github.com/users/mad-skull/following{/other_user}",
    gists_url: "https://api.github.com/users/mad-skull/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/mad-skull/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mad-skull/subscriptions",
    organizations_url: "https://api.github.com/users/mad-skull/orgs",
    repos_url: "https://api.github.com/users/mad-skull/repos",
    events_url: "https://api.github.com/users/mad-skull/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/mad-skull/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Harshit101",
    id: 68851827,
    node_id: "MDQ6VXNlcjY4ODUxODI3",
    avatar_url: "https://avatars.githubusercontent.com/u/68851827?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Harshit101",
    html_url: "https://github.com/Harshit101",
    followers_url: "https://api.github.com/users/Harshit101/followers",
    following_url:
      "https://api.github.com/users/Harshit101/following{/other_user}",
    gists_url: "https://api.github.com/users/Harshit101/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Harshit101/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Harshit101/subscriptions",
    organizations_url: "https://api.github.com/users/Harshit101/orgs",
    repos_url: "https://api.github.com/users/Harshit101/repos",
    events_url: "https://api.github.com/users/Harshit101/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Harshit101/received_events",
    type: "User",
    site_admin: false,
  },
];
